spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppdb
    username: propick
    password: propick
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

#  profiles:
#    active: user   # 기본 프로파일 설정
  profiles:
    active: admin
  web:
    resources:
      static-locations: >
        classpath:/static/,
        classpath:/public/,
        classpath:/resources/,
        classpath:/META-INF/resources/,
        classpath:/static/management/,
        file:uploads/,
        file:/absolute/path/to/uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.springframework: INFO
    com.ezen.propick: INFO

  # Thymeleaf 설정 추가
  thymeleaf:
    prefix: classpath:/templates/main/  # main 폴더를 포함한 경로 설정
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
